### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [chronoly/vscode-chronoly-plugin#18]
#### **Problem**

I've been waiting for a few minutes:

> ![Screenshot_20241021_204417](https://github.com/user-attachments/assets/7e9c1550-bf11-427f-bb7c-c27288374003)

#### **Environment**
	
-	1.	```sh
		rpm -qa 'code'
		```
		
	1.	> ```log
		> code-1.94.2-1728494086.el8.x86_64
		> ```

-	1.	```sh
		kinfo
		```
		
	1.	> ```YAML
		>       Operating System: Fedora Linux 40
		>     KDE Plasma Version: 6.2.1
		> KDE Frameworks Version: 6.7.0
		>             Qt Version: 6.7.2
		>         Kernel Version: 6.11.4-200.fc40.x86_64 (64-bit)
		>      Graphics Platform: Wayland
		>             Processors: 12 × AMD Ryzen 5 7600X 6-Core Processor
		>                 Memory: 30.4 GiB of RAM
		>     Graphics Processor: AMD Radeon RX 5700
		> ```

**Comment by beedell-roke** [comment]
> https://github.com/chronoly/vscode-chronoly-plugin/issues/18#issue-2603511536

Huh - it installed whilst I authored this. It just took an inordinate amount of time, was all.
